name: Build

on:
  push:
#    paths:
#      - "bookmarker-api/**"
    branches: [ "master" ]
  pull_request:
#    paths:
#      - "bookmarker-api/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-bookmarker-api:
    name: Build bookmarker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api
    steps:
      - uses: actions/checkout@v4

      - name: Set execute permissions for mvnw
        run: chmod +x ./mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build and Publish Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          ./mvnw compile jib:build
